// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: healthcheck/v1/health.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckResponse_ServiceStatus int32

const (
	HealthCheckResponse_UNKNOWN         HealthCheckResponse_ServiceStatus = 0
	HealthCheckResponse_SERVING         HealthCheckResponse_ServiceStatus = 1
	HealthCheckResponse_NOT_SERVING     HealthCheckResponse_ServiceStatus = 2
	HealthCheckResponse_SERVICE_UNKNOWN HealthCheckResponse_ServiceStatus = 3
)

// Enum value maps for HealthCheckResponse_ServiceStatus.
var (
	HealthCheckResponse_ServiceStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
		3: "SERVICE_UNKNOWN",
	}
	HealthCheckResponse_ServiceStatus_value = map[string]int32{
		"UNKNOWN":         0,
		"SERVING":         1,
		"NOT_SERVING":     2,
		"SERVICE_UNKNOWN": 3,
	}
)

func (x HealthCheckResponse_ServiceStatus) Enum() *HealthCheckResponse_ServiceStatus {
	p := new(HealthCheckResponse_ServiceStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServiceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServiceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_healthcheck_v1_health_proto_enumTypes[0].Descriptor()
}

func (HealthCheckResponse_ServiceStatus) Type() protoreflect.EnumType {
	return &file_healthcheck_v1_health_proto_enumTypes[0]
}

func (x HealthCheckResponse_ServiceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServiceStatus.Descriptor instead.
func (HealthCheckResponse_ServiceStatus) EnumDescriptor() ([]byte, []int) {
	return file_healthcheck_v1_health_proto_rawDescGZIP(), []int{0, 0}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        HealthCheckResponse_ServiceStatus `protobuf:"varint,1,opt,name=status,proto3,enum=healthcheck.v1.HealthCheckResponse_ServiceStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_healthcheck_v1_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_healthcheck_v1_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_healthcheck_v1_health_proto_rawDescGZIP(), []int{0}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServiceStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

var File_healthcheck_v1_health_proto protoreflect.FileDescriptor

const file_healthcheck_v1_health_proto_rawDesc = "" +
	"\n" +
	"\x1bhealthcheck/v1/health.proto\x12\x0ehealthcheck.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xb1\x01\n" +
	"\x13HealthCheckResponse\x12I\n" +
	"\x06status\x18\x01 \x01(\x0e21.healthcheck.v1.HealthCheckResponse.ServiceStatusR\x06status\"O\n" +
	"\rServiceStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x02\x12\x13\n" +
	"\x0fSERVICE_UNKNOWN\x10\x032v\n" +
	"\x12HealthCheckService\x12`\n" +
	"\vHealthCheck\x12\x16.google.protobuf.Empty\x1a#.healthcheck.v1.HealthCheckResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/healthcheckB\x17Z\x15api/healthcheck/v1;v1b\x06proto3"

var (
	file_healthcheck_v1_health_proto_rawDescOnce sync.Once
	file_healthcheck_v1_health_proto_rawDescData []byte
)

func file_healthcheck_v1_health_proto_rawDescGZIP() []byte {
	file_healthcheck_v1_health_proto_rawDescOnce.Do(func() {
		file_healthcheck_v1_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_healthcheck_v1_health_proto_rawDesc), len(file_healthcheck_v1_health_proto_rawDesc)))
	})
	return file_healthcheck_v1_health_proto_rawDescData
}

var file_healthcheck_v1_health_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_healthcheck_v1_health_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_healthcheck_v1_health_proto_goTypes = []any{
	(HealthCheckResponse_ServiceStatus)(0), // 0: healthcheck.v1.HealthCheckResponse.ServiceStatus
	(*HealthCheckResponse)(nil),            // 1: healthcheck.v1.HealthCheckResponse
	(*emptypb.Empty)(nil),                  // 2: google.protobuf.Empty
}
var file_healthcheck_v1_health_proto_depIdxs = []int32{
	0, // 0: healthcheck.v1.HealthCheckResponse.status:type_name -> healthcheck.v1.HealthCheckResponse.ServiceStatus
	2, // 1: healthcheck.v1.HealthCheckService.HealthCheck:input_type -> google.protobuf.Empty
	1, // 2: healthcheck.v1.HealthCheckService.HealthCheck:output_type -> healthcheck.v1.HealthCheckResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_healthcheck_v1_health_proto_init() }
func file_healthcheck_v1_health_proto_init() {
	if File_healthcheck_v1_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_healthcheck_v1_health_proto_rawDesc), len(file_healthcheck_v1_health_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_healthcheck_v1_health_proto_goTypes,
		DependencyIndexes: file_healthcheck_v1_health_proto_depIdxs,
		EnumInfos:         file_healthcheck_v1_health_proto_enumTypes,
		MessageInfos:      file_healthcheck_v1_health_proto_msgTypes,
	}.Build()
	File_healthcheck_v1_health_proto = out.File
	file_healthcheck_v1_health_proto_goTypes = nil
	file_healthcheck_v1_health_proto_depIdxs = nil
}
