// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v5.29.3
// source: healthcheck/v1/health.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationHealthCheckServiceHealthCheck = "/healthcheck.v1.HealthCheckService/HealthCheck"

type HealthCheckServiceHTTPServer interface {
	HealthCheck(context.Context, *emptypb.Empty) (*HealthCheckResponse, error)
}

func RegisterHealthCheckServiceHTTPServer(s *http.Server, srv HealthCheckServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/healthcheck", _HealthCheckService_HealthCheck0_HTTP_Handler(srv))
}

func _HealthCheckService_HealthCheck0_HTTP_Handler(srv HealthCheckServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHealthCheckServiceHealthCheck)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.HealthCheck(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HealthCheckResponse)
		return ctx.Result(200, reply)
	}
}

type HealthCheckServiceHTTPClient interface {
	HealthCheck(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *HealthCheckResponse, err error)
}

type HealthCheckServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewHealthCheckServiceHTTPClient(client *http.Client) HealthCheckServiceHTTPClient {
	return &HealthCheckServiceHTTPClientImpl{client}
}

func (c *HealthCheckServiceHTTPClientImpl) HealthCheck(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*HealthCheckResponse, error) {
	var out HealthCheckResponse
	pattern := "/healthcheck"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHealthCheckServiceHealthCheck))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
